# https://doc-snapshots.qt.io/qt6-6.4/supported-platforms.html
c_stdlib_version:          # [osx and x86_64]
  - '10.14'                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - '11.0'                 # [osx and x86_64]
# Use newer MSVC compiler, because MSVC 2019 is broken and produces an internal compiler error when building the C++20 code of OVITO 3.11+:
c_compiler:    # [win]
  - vs2022     # [win]
cxx_compiler:  # [win]
  - vs2022     # [win]
