{% set name = "ovito" %}
{% set version = "2.9.0" %}
{% set sha256 = "c6fe3cecb2ed08ead96606eeea1818c0c98468f665ab57363538ab225e603247" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/stuko/ovito/-/archive/master/ovito-master.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - qscintilla2
    - sphinx
    - cmake =3.11
    - make 
    - fftw 
    - libglu
    - git
    - boost =1.57.0
    - libstdcxx-ng =5.4.0
    - qt
    - libgcc-ng =5.4.0
    - zlib
  host:
    - python
    - pip
    - numpy 
    - sip 
    - pyqt =5.6.0
    - matplotlib
    - ase
  run:
    - python
    - numpy 
    - sip 
    - pyqt =5.6.0
    - matplotlib
    - ase
    - qscintilla2
    - fftw
    - libglu
    - boost =1.57.0
    - libstdcxx-ng =5.4.0
    - qt
    - libgcc-ng =5.4.0
    - zlib

test:
  imports:
    - ovito

about:
  home: https://www.ovito.org
  license: GPL-3.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Scientific visualization and analysis software for atomistic simulation data'
  description: |
    OVITO is a scientific visualization and analysis software for 
    atomistic and particle simulation data. It helps scientists gain 
    better insights into materials phenomena and physical processes. 
    OVITO is being developed by Alexander Stukowski at Darmstadt 
    University of Technology, Germany.
  doc_url: http://www.ovito.org/
  dev_url: https://gitlab.com/stuko/ovito

extra:
  recipe-maintainers:
    - jan-janssen
