{% set name = "ovito" %}
{% set version = "3.1.0" %}
{% set sha256 = "afd15d5eb3b0d4b29ef9133919d677c409bd11771a9b5abf12b9869ce58ece3c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/stuko/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - gcc_7_2.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - sphinx
    - cmake
    - make
    - git
  host:
    - xorg-libxfixes  # [linux]
    - qt
    - python
    - numpy
    - pyqt
    - qscintilla2
    - boost =1.57.0
    - zlib
    - fftw
  run:
    - python
    - matplotlib
    - ase

test:
  imports:
    - ovito

about:
  home: https://www.ovito.org
  license: GPL-3.0
  license_family: GPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: Scientific visualization and analysis software for atomistic simulation data
  description: |
    OVITO is a scientific visualization and analysis software for
    atomistic and particle simulation data. It helps scientists gain
    better insights into materials phenomena and physical processes.
    OVITO is being developed by Alexander Stukowski at Darmstadt
    University of Technology, Germany.
  doc_url: http://www.ovito.org/
  dev_url: https://gitlab.com/stuko/ovito

extra:
  recipe-maintainers:
    - jan-janssen
